apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        email: flux@justneverlift.com
        name: Flux Bot
    checkout:
      ref:
        branch: master
    push:
      branch: master
  update:
    path: ./clusters/my-cluster/justneverlift.com
    strategy: Setters
